pub mod cli_error;
pub mod create_customer;
pub mod create_invoice;
pub mod get_customer;
pub mod init;
pub mod context_parameters;
pub mod get_invoice;
pub mod delete_invoice;
mod utils;
pub mod list_invoices;
pub mod list_customers;
pub mod delete_customer;
pub mod edit_customer;
pub mod month_stats;
pub mod year_stats;
pub mod day_stats;
pub mod get_settings;
pub mod edit_settings;
